### ISSUE TITLE
Feature Request: GNMI Union Replace

### ISSUE THREAD

**Issue by mojiiba** [openconfig/ygnmi#124]
Could you please add support for GNMI Union Replace. The detail for gnmi union replace is described here: [https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-union_replace.md](https://www.google.com/url?q=https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-union_replace.md&sa=D&source=buganizer&usg=AOvVaw2Yws7mj9NjrppvU8XbO0QA)

**Comment by greg-dennis** [comment]
Heh, @wenovus fixed this very quickly earlier today in https://github.com/openconfig/ygnmi/pull/123
What's left for Ondatra support:
1. Pull this new ygnmi version into google3
2. Add wrapper functions to Ondatra for BatchUnionReplace and BatchUnionReplaceCLI
3. Push a new version of Ondatra externally
4. Update featureprofiles deps to require the new Ondatra version

I am going on vacation for two weeks starting on Monday morning. @wenovus, can you take it from here?

**Comment by wenovus** [comment]
Sure I can take a look.

**Comment by wenovus** [comment]
Featureprofiles PR at https://github.com/openconfig/featureprofiles/pull/2018
