### ISSUE TITLE
Support for gpb.GetRequest

### ISSUE THREAD

**Issue by fmolinar** [openconfig/ygnmi#149]
Currently, there is support for ONCE subscriptions using the Get and GetAll functions, which utilize ygnmi.GetAll and ygnmi.Get, and subsequently call Lookup. For testing purposes and as an alternative, it would be beneficial to have a function that uses gpb.GetRequest instead of subscribing. This would mimic the gnmic approach of subscribe and get, providing more flexibility in testing scenarios.

**Comment by DanG100** [comment]
You can use the [WithUseGet()](https://github.com/openconfig/ygnmi/blob/a0fdb565dc4c80f8151bb0469285f1063d8a4fdc/ygnmi/ygnmi.go#L217) Option to  use gnmi.Get RPC instead of Subscribe RPC.
