### ISSUE TITLE
initiate the client

### ISSUE THREAD

**Issue by BouchardClaude** [openconfig/ygnmi#88]
Hi ! Would it be possible to have an example on how to properly Initialize ygnmi.Client ? 
I'M a bit confused as im not able to init it the same way I do with the gnmi client. 

Thanks!!

**Comment by DanG100** [comment]
To create a client, use the NewClient func. https://pkg.go.dev/github.com/openconfig/ygnmi/ygnmi#NewClient

something like 
```go
conn, err := grpc.Dial(addr)
gnmiC := gpb.NewGNMIClient(conn)
c, err := ygnmi.NewClient(gnmiC)
```

**Comment by BouchardClaude** [comment]
Thanks for the help! not sure why I missed the part where I needed to use NewClient.. was using Client.
